# Generated by Django 3.1.7 on 2021-03-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ZcId', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='ZcId')),
                ('ZcName', models.CharField(max_length=255, verbose_name='ZcName')),
                ('UsePart', models.CharField(max_length=255, verbose_name='UsePart')),
                ('UsePeople', models.CharField(max_length=255, verbose_name='UsePeople')),
                ('UseLocat', models.CharField(max_length=255, verbose_name='UseLocat')),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('modifyTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ZcTable',
            },
        ),
    ]
