# Generated by Django 3.1.7 on 2021-03-19 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asset_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Zc',
        ),
    ]
