# Generated by Django 3.1.7 on 2021-03-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset_management', '0003_auto_20210319_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zc',
            name='ZcId',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='ZcId'),
        ),
    ]
