# Generated by Django 3.1.7 on 2021-03-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset_management', '0004_auto_20210319_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='zc',
            name='Text',
            field=models.CharField(max_length=255, null=True, verbose_name='Text'),
        ),
    ]
