# Generated by Django 3.1.7 on 2021-03-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset_management', '0005_zc_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='zc',
            name='img1',
            field=models.TextField(blank=True, null=True, verbose_name='img1'),
        ),
        migrations.AddField(
            model_name='zc',
            name='img2',
            field=models.TextField(blank=True, null=True, verbose_name='img2'),
        ),
        migrations.AddField(
            model_name='zc',
            name='img3',
            field=models.TextField(blank=True, null=True, verbose_name='img3'),
        ),
        migrations.AlterField(
            model_name='zc',
            name='Text',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
    ]
