# Generated by Django 3.1.7 on 2021-03-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset_management', '0007_auto_20210320_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zc',
            name='ZcId',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False, verbose_name='ZcId'),
        ),
    ]
